### ISSUE TITLE
1.15.2 =1.16.1

### ISSUE THREAD

**Issue by Gunnarmeloenar** [JamiesWhiteShirt/trumpet-skeleton#10]
Hello,

if I install the mod 1.15.2 version on forge it says that it is a 1.16.1 version. 
How do I fix it?

**Comment by JamiesWhiteShirt** [comment]
[Go to the Trumpet Skeleton: ReDooted issue tracker.](https://github.com/gdude2002/trumpet-skeleton/issues/1)
