### ISSUE TITLE
Server crashes when player joins

### ISSUE THREAD

**Issue by rijenkii** [JamiesWhiteShirt/trumpet-skeleton#5]
[Crash log](https://pastebin.com/raw/U4Ddbuzh)

**Comment by rijenkii** [comment]
Everything works with version 1.0.1.2, but not with 1.0.2.0

**Comment by JamiesWhiteShirt** [comment]
Thanks for the report. It seems the Minecraft Development plugin for IntelliJ failed me this time.

Version 1.0.2.1 should resolve this. It should be available on CurseForge any moment now.
